=== rafikchb/static-site-from-xml/Recettes.dtd
<!ELEMENT Recettes (Recette+, Ingredients+ , Auteurs , Categorie_plats , Produits)>
        <!ELEMENT Recette (Titre ,Resume ,Photo , Date_publication , Dificulte , Recette_ingredients ,
                Nombre_perssone ,Temp_preparation, Temp_cuisson , Temp_repos  ,Description_preparation ,
                Note , Recette_auteurs )>
        <!ATTLIST Recette recette_id ID #REQUIRED>
        <!ELEMENT Titre (#PCDATA)>
        <!ELEMENT Resume (#PCDATA)>
        <!ELEMENT Photo (Url , Description)>
        <!ELEMENT Url (#PCDATA)>
        <!ELEMENT Description (#PCDATA)>
        <!ELEMENT Date_publication (#PCDATA)>
        <!ELEMENT Dificulte (#PCDATA)>
        <!ELEMENT Recette_ingredients (Recette_ingredient+)>
        <!ELEMENT Recette_ingredient EMPTY>
        <!ATTLIST Recette_ingredient Recette_ingredient_id IDREF #REQUIRED>
        <!ELEMENT Nombre_perssone (#PCDATA)>
        <!ELEMENT Temp_preparation (#PCDATA)>
        <!ELEMENT Temp_cuisson (#PCDATA)>
        <!ELEMENT Temp_repos (#PCDATA)>


        <!ELEMENT Description_preparation (#PCDATA |p | ul | table)* >
        <!ELEMENT p (#PCDATA | b | i | a | br | strong | t |p)*>
        <!ELEMENT b (#PCDATA)>
        <!ELEMENT i (#PCDATA)>
        <!ELEMENT a (#PCDATA)>
        <!ATTLIST a href CDATA #REQUIRED>
        <!ELEMENT br EMPTY>
        <!ELEMENT strong (#PCDATA)>
        <!ELEMENT t (#PCDATA)>

        <!ELEMENT ul (li)*>
        <!ELEMENT li (p)>
        <!ELEMENT table (thead?, tfoot?, tbody+)>
        <!ELEMENT thead (tr)>
        <!ELEMENT tfoot (tr)>
        <!ELEMENT tbody (tr+)>
        <!ELEMENT tr (th|td)+>
        <!ELEMENT th (#PCDATA)>
        <!ELEMENT td (#PCDATA) >

        <!ELEMENT Note (#PCDATA)>
        <!ELEMENT Recette_auteurs (Recette_auteur+)>
        <!ELEMENT Recette_auteur EMPTY>
        <!ATTLIST Recette_auteur Recette_auteur_id IDREF #REQUIRED >
        <!ELEMENT Ingredients (Ingredient )+ >
        <!ELEMENT Ingredient (Ingredient_nom , Apport_energetique , Saison , Descriptif )>
        <!ATTLIST Ingredient ingredient_id ID #REQUIRED>
        <!ELEMENT Ingredient_nom (#PCDATA)>
        <!ELEMENT Apport_energetique (#PCDATA)>
        <!ELEMENT Saison (#PCDATA)>
        <!ELEMENT Descriptif (#PCDATA | p | ul | table)*>
        <!ELEMENT Auteurs (Auteur+)>

        <!ELEMENT Auteur (Auteur_Nom,Auteur_Prenom, Age,Pays,Sexe,Bibliographie,Auteur_recettes)>
        <!ATTLIST Auteur Auteur_id ID #REQUIRED>
        <!ELEMENT Auteur_Nom (#PCDATA)>
        <!ELEMENT Auteur_Prenom (#PCDATA)>
        <!ELEMENT Age (#PCDATA)>
        <!ELEMENT Pays (#PCDATA)>
        <!ELEMENT Sexe (#PCDATA)>
        <!ELEMENT Bibliographie (#PCDATA)>
        <!ELEMENT Auteur_recettes (Auteur_recette*)>
        <!ELEMENT Auteur_recette EMPTY>
        <!ATTLIST Auteur_recette auteur_recette_id IDREF #REQUIRED >

        <!ELEMENT Categorie_plats (Categorie_plat+)>

        <!ELEMENT Categorie_plat (Categorie_plat_nom ,Categorie_plat_desription , Sous_categorie_plat* ) >
       <!ATTLIST Categorie_plat Categorie_plats_id ID #REQUIRED>
        <!ELEMENT Categorie_plat_nom (#PCDATA)>
        <!ELEMENT Categorie_plat_desription (#PCDATA | p | ul | table)*>
        <!ELEMENT Sous_categorie_plat (Sous_categorie_plat_nom,Sous_categorie_plat_description?,Sous_categorie_plat_recettes?)>
        <!ATTLIST Sous_categorie_plat Categorie_plats_id ID #REQUIRED>
        <!ELEMENT Sous_categorie_plat_nom (#PCDATA)>
        <!ELEMENT Sous_categorie_plat_description (#PCDATA | p | ul | table)*>
        <!ELEMENT Sous_categorie_plat_recettes (Sous_categorie_plat_recette*)>
        <!ELEMENT Sous_categorie_plat_recette EMPTY>
        <!ATTLIST Sous_categorie_plat_recette Sous_categorie_plat_recette_id IDREF #REQUIRED>

        <!ELEMENT Produits (Produit)+>
<!ATTLIST Produit produit_id ID #REQUIRED>
        <!ELEMENT Produit (Produit_Nom ,Produit_Ingredients)>
        <!ELEMENT Produit_Nom (#PCDATA)>
        <!ELEMENT Produit_Ingredients (Produit_Ingredient+) >
        <!ELEMENT Produit_Ingredient EMPTY>
        <!ATTLIST Produit_Ingredient Produit_Ingredient_id IDREF #REQUIRED>

=== rafikchb/static-site-from-xml/transformedDonneesRecetts.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Recettes
  SYSTEM "Recettes.dtd">
<Recettes>
   <Recette recette_id="r2830">
      <Titre>Cake à la tomate farcie</Titre>
      <Resume>Cake à la tomate farcie - Recettes de cuisine Ôdélices</Resume>
      <Photo>
         <Url>http://www.odelices.com/images/recettes/cake-a-la-tomate-farcie.jpg</Url>
         <Description>
                    image
                </Description>
      </Photo>
      <Date_publication>2011-04-24</Date_publication>
      <Dificulte>Très facile</Dificulte>
      <Recette_ingredients>
         <Recette_ingredient Recette_ingredient_id="F120"/>
         <Recette_ingredient Recette_ingredient_id="L300"/>
         <Recette_ingredient Recette_ingredient_id="L50"/>
         <Recette_ingredient Recette_ingredient_id="O12"/>
         <Recette_ingredient Recette_ingredient_id="H20"/>
         <Recette_ingredient Recette_ingredient_id="t142"/>
         <Recette_ingredient Recette_ingredient_id="F10"/>
         <Recette_ingredient Recette_ingredient_id="t120"/>
         <Recette_ingredient Recette_ingredient_id="S12"/>
         <Recette_ingredient Recette_ingredient_id="Po40"/>
      </Recette_ingredients>
      <Nombre_perssone>6</Nombre_perssone>
      <Temp_preparation>20min</Temp_preparation>
      <Temp_cuisson>25min</Temp_cuisson>
      <Temp_repos/>
      <Description_preparation>
         <p>1. Inciser le fond de chaque tomate et vider les graines à l'aide d'une toute petite cuillère (j'ai fait
                avec le manche d'une cuillère à moka).
                Saler l'intérieur de chaque tomate et déposer sur un papier absorbant, elles vont dégorger.
                <br/>
                2. Beurrer et fariner 6 ramequins. Préchauffer le four à 180°C.
                <br/>
                3. Faire tiédir le lait 20-30 secondes au micro-onde. Battre l'oeuf en omelette, saler et poivrer puis
                ajouter la farine, la levure, le lait et l'huile.
                Ajouter le fromage râpé.
                <br/>
                4. Dans un bol mélanger la fêta et le thon égoutté à l'aide d'une fourchette et farcir les tomates avec
                cette préparation.
                <br/>
                5. Remplir les moules avec la pâte et déposer une tomate dans chaque en l'enfonçant au deux tiers du
                moule.
                <br/>
                6. Cuire entre 20 et 25 minutes.
            </p>
      </Description_preparation>
      <Note/>
      <Recette_auteurs>
         <Recette_auteur Recette_auteur_id="AUT3"/>
      </Recette_auteurs>
   </Recette>
   <Recette recette_id="r3136">
      <Titre>Petits cakes au chèvre frais et myrtilles</Titre>
      <Resume>Petits cakes au chèvre frais et myrtilles - les meilleures recettes de cuisine d'Ôdélices</Resume>
      <Photo>
         <Url>http://www.odelices.com/images/recettes/petits-cakes-au-chevre-frais-et-myrtilles.jpg</Url>
         <Description>
                    image
                </Description>
      </Photo>
      <Date_publication>2012-04-09</Date_publication>
      <Dificulte>Très facile</Dificulte>
      <Recette_ingredients>
         <Recette_ingredient Recette_ingredient_id="F120"/>
         <Recette_ingredient Recette_ingredient_id="L50"/>
         <Recette_ingredient Recette_ingredient_id="O12"/>
         <Recette_ingredient Recette_ingredient_id="H20"/>
         <Recette_ingredient Recette_ingredient_id="FC20"/>
         <Recette_ingredient Recette_ingredient_id="B200"/>
         <Recette_ingredient Recette_ingredient_id="M110"/>
      </Recette_ingredients>
      <Nombre_perssone>6</Nombre_perssone>
      <Temp_preparation>10min</Temp_preparation>
      <Temp_cuisson>17min</Temp_cuisson>
      <Temp_repos/>
      <Description_preparation>
         <p>1. Dans un saladier, mélangez la farine, le sel, le bicarbonate, les oeufs, le lait et l'huile.
                <br/>
                2. Quand la pâte est belle, versez-la dans de petits moules à cake huilés.
                <br/>
                3. Répartissez sur les cakes de petits morceaux de fromage et les myrtilles.
                <br/>
                4. Faites cuire 17 minutes à 180°C four ventilé. Piquez un cake à l'aide de la pointe d'un couteau afin
                de vérifier la cuisson.
                <br/>
                5. Servez à température ambiante avec une salade croquante.
                <br/>
            </p>
      </Description_preparation>
      <Note>5</Note>
      <Recette_auteurs>
         <Recette_auteur Recette_auteur_id="AUT2"/>
      </Recette_auteurs>
   </Recette>
   <Recette recette_id="r4275">
      <Titre>Mozzarella panée</Titre>
      <Resume>Pour un soir de semaine, si vous voulez faire une salade express mais épatante, faites de la
                    mozzarella panée ! C'est rapide, facile et très syma !
                </Resume>
      <Photo>
         <Url>http://www.odelices.com/images/recettes/mozzarella_panee.jpg</Url>
         <Description>
                    image
                </Description>
      </Photo>
      <Date_publication>2015-02-08</Date_publication>
      <Dificulte>Très facile</Dificulte>
      <Recette_ingredients>
         <Recette_ingredient Recette_ingredient_id="B10"/>
         <Recette_ingredient Recette_ingredient_id="O12"/>
         <Recette_ingredient Recette_ingredient_id="F120"/>
         <Recette_ingredient Recette_ingredient_id="CH12"/>
      </Recette_ingredients>
      <Nombre_perssone>4</Nombre_perssone>
      <Temp_preparation>5min</Temp_preparation>
      <Temp_cuisson>5min</Temp_cuisson>
      <Temp_repos/>
      <Description_preparation>
         <p>1. Coupez les boules de mozzarella en rondelles.
                <br/>
                2. Mettez la farine et la chapelure dans deux assiettes. Et battez l'oeuf avec une fourchette dans un
                bol.
                <br/>
                3. Faites chauffer une poêle avec de l'huile.
                <br/>
                4. Faites tremper les rondelles de mozzarella dans la farine, puis dans l'oeuf et enfin dans la
                chapelure.
                <br/>
                5. Faites frire dans la poêle quelques minutes de chaque côté. Servez avec une salade verte.
                <br/>
            </p>
      </Description_preparation>
      <Note>5</Note>
      <Recette_auteurs>
         <Recette_auteur Recette_auteur_id="AUT1"/>
      </Recette_auteurs>
   </Recette>
   <Recette recette_id="r3289">
      <Titre>Oeuf cocotte aux marrons</Titre>
      <Resume/>
      <Photo>
         <Url>http://www.odelices.com/images/recettes/oeuf_cocotte_aux_marrons.jpg</Url>
         <Description>
                    image
                </Description>
      </Photo>
      <Date_publication>2012-11-22</Date_publication>
      <Dificulte>Très facile</Dificulte>
      <Recette_ingredients>
         <Recette_ingredient Recette_ingredient_id="M9"/>
         <Recette_ingredient Recette_ingredient_id="O12"/>
         <Recette_ingredient Recette_ingredient_id="C50"/>
         <Recette_ingredient Recette_ingredient_id="S12"/>
         <Recette_ingredient Recette_ingredient_id="Po40"/>
      </Recette_ingredients>
      <Nombre_perssone>4</Nombre_perssone>
      <Temp_preparation>5min</Temp_preparation>
      <Temp_cuisson>15min</Temp_cuisson>
      <Temp_repos/>
      <Description_preparation>
         <p>1. Hachez grossièrement les marrons cuits. Répartissez-les dans 4 ramequins inviduels.
                <br/>
                2. Répartissez une cuillère de crème sur les marrons.
                <br/>
                3. Puis cassez les oeufs et ajoutez-en un dans chaque ramequin, en les posant délicatement pour ne pas
                casser le jaune. Salez et poivrez.
                <br/>
                4. Placez les ramequins dans le four préchauffé à 180°C, au bain-marie. Faites cuire 15 min jusqu'à ce
                que le blanc soit bien pris.
                <br/>
                5. Servez chaud, avec des mouillettes de pain grillé.
                <br/>
            </p>
      </Description_preparation>
      <Note/>
      <Recette_auteurs>
         <Recette_auteur Recette_auteur_id="AUT1"/>
      </Recette_auteurs>
   </Recette>
   <Recette recette_id="r4315">
      <Titre>Endives farcies au thon</Titre>
      <Resume>

                    Une salade « hébergée » dans une feuille d'endive ! Une idée gourmande qui ravira les plus jeunes
                    qui pourront d'ailleurs vous aider à farcir les endives !
                </Resume>
      <Photo>
         <Url>http://www.odelices.com/images/recettes/endives_farcies_au_thon1.jpg</Url>
         <Description>
                    image
                </Description>
      </Photo>
      <Date_publication>2015-03-12</Date_publication>
      <Dificulte>Très facile</Dificulte>
      <Recette_ingredients>
         <Recette_ingredient Recette_ingredient_id="e300"/>
         <Recette_ingredient Recette_ingredient_id="t120"/>
         <Recette_ingredient Recette_ingredient_id="Co30"/>
         <Recette_ingredient Recette_ingredient_id="C50"/>
         <Recette_ingredient Recette_ingredient_id="M80"/>
         <Recette_ingredient Recette_ingredient_id="CI10"/>
         <Recette_ingredient Recette_ingredient_id="t142"/>
         <Recette_ingredient Recette_ingredient_id="S12"/>
         <Recette_ingredient Recette_ingredient_id="Po40"/>
      </Recette_ingredients>
      <Nombre_perssone>4</Nombre_perssone>
      <Temp_preparation>15min</Temp_preparation>
      <Temp_cuisson/>
      <Temp_repos/>
      <Description_preparation>
         <p>1. Lavez les tomates, coupez-les en deux et épépinez-les. Emincez finement la ciboulette.
                <br/>
                2. Mettez dans le bol du robot le thon, les tomates, les cornichons, la crème fraîche, la moutarde et la
                ciboulette. Mixez le tout grossièrement pour garder quelques morceaux. Salez légèrement et poivrez
                éventuellement.
